VALID_AIRPORTS_DATA = [
    [
        "26396",
        "UUEE",
        "large_airport",
        "Sheremetyevo International Airport",
        "55.972599",
        "37.4146",
        "622",
        "EU",
        "RU",
        "RU-MOS",
        "Moscow",
        "yes",
        "UUEE",
        "SVA",
        "UUEE",
        "",
        "http://svo.aero/en/",
        "https://en.wikipedia.org/wiki/Sheremetyevo_International_Airport",
        "MOW, Международный аэропорт Шереметьево, svo, sheremetyevo, moscow",
    ],
    [
        "27223",
        "ZSPD",
        "large_airport",
        "Shanghai Pudong International Airport",
        "31.1434",
        "121.805",
        "13",
        "AS",
        "CN",
        "CN-31",
        "Shanghai (Pudong)",
        "yes",
        "ZSPD",
        "PVQ",
        "ZSPD",
        "",
        "https://www.shanghaiairport.com/index.html",
        "https://en.wikipedia.org/wiki/Shanghai_Pudong_International_Airport",
        "",
    ],
]

AIRPORTS_DATA_WITH_SKIPPED = [
    [
        "26396",
        "UUEE",
        "large_airport",
        "Sheremetyevo International Airport",
        "55.972599",
        "37.4146",
        "622",
        "EU",
        "RU",
        "RU-MOS",
        "Moscow",
        "yes",
        "UUEE",
        "SVO",
        "UUEE",
        "",
        "http://svo.aero/en/",
        "https://en.wikipedia.org/wiki/Sheremetyevo_International_Airport",
        "MOW, Международный аэропорт Шереметьево, svo, sheremetyevo, moscow",
    ],
    [
        "26396",
        "UUEE",
        "large_airport",
        "Sheremetyevo International Airport",
        "55.972599",
        "37.4146",
        "622",
        "EU",
        "RU",
        "RU-MOS",
        "Moscow",
        "yes",
        "UUEE",
        "SVO",
        "UUEE",
        "",
        "http://svo.aero/en/",
        "https://en.wikipedia.org/wiki/Sheremetyevo_International_Airport",
        "MOW, Международный аэропорт Шереметьево, svo, sheremetyevo, moscow",
    ],
]

INVALID_AIRPORTS_DATA = [
    [
        "26396",
        "UUEE1313",
        "large_airport",
        "Sheremetyevo International Airport",
        "55.972599",
        "37.4146",
        "622",
        "EU",
        "RU",
        "RU-MOS",
        "Moscow",
        "yes",
        "UUEE35353",
        "SVO3535",
        "UUEE4343",
        "",
        "http://svo.aero/en/",
        "https://en.wikipedia.org/wiki/Sheremetyevo_International_Airport",
        "MOW, Международный аэропорт Шереметьево, svo, sheremetyevo, moscow",
    ],
    [
        "27223",
        "ZSPD3131",
        "large_airport",
        "Shanghai Pudong International Airport",
        "31.1434",
        "121.805",
        "13",
        "AS",
        "CN",
        "CN-31",
        "Shanghai (Pudong)",
        "yes",
        "ZSPD111",
        "PVG4343",
        "ZSPD434",
        "",
        "https://www.shanghaiairport.com/index.html",
        "https://en.wikipedia.org/wiki/Shanghai_Pudong_International_Airport",
        "",
    ],
]
