"""Initial migration

Revision ID: 1d4d2aa2c4e1
Revises: 95fd3802e554
Create Date: 2025-08-08 23:00:48.346020

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d4d2aa2c4e1"
down_revision: str | None = "95fd3802e554"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("airports", sa.Column("name_russian", sa.String(), nullable=True))
    op.drop_column("airports", "name_russion")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("airports", sa.Column("name_russion", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("airports", "name_russian")
    # ### end Alembic commands ###
