"""cities

Revision ID: 3fde5d9e2575
Revises: 7f54ac0c4001
Create Date: 2025-08-10 14:04:18.792224

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fde5d9e2575"
down_revision: str | None = "7f54ac0c4001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("name_english", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_id"), "cities", ["id"], unique=False)
    op.add_column("airports", sa.Column("city_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_airports_city_id"), "airports", ["city_id"], unique=False)
    op.create_foreign_key(None, "airports", "cities", ["city_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "airports", type_="foreignkey")
    op.drop_index(op.f("ix_airports_city_id"), table_name="airports")
    op.drop_column("airports", "city_id")
    op.drop_index(op.f("ix_cities_id"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
