"""regions

Revision ID: 6386416f5fe5
Revises: d533a6a57e91
Create Date: 2025-08-10 00:21:28.600866

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6386416f5fe5"
down_revision: str | None = "d533a6a57e91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("regions", sa.Column("name_english", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regions", "name_english")
    # ### end Alembic commands ###
