"""Init tickets

Revision ID: 67ef4354ebee
Revises: 1d4d2aa2c4e1
Create Date: 2025-08-09 03:12:06.465893

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67ef4354ebee"
down_revision: str | None = "1d4d2aa2c4e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin_airport_id", sa.Integer(), nullable=True),
        sa.Column("destination_airport_id", sa.Integer(), nullable=True),
        sa.Column("departure_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("return_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["destination_airport_id"],
            ["airports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_airport_id"],
            ["airports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickets_id"), "tickets", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_id"), table_name="tickets")
    op.drop_table("tickets")
    # ### end Alembic commands ###
