"""cities

Revision ID: 8bbfb0199e05
Revises: 3fde5d9e2575
Create Date: 2025-08-10 14:05:57.879790

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bbfb0199e05"
down_revision: str | None = "3fde5d9e2575"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("airports", "municipality")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("airports", sa.Column("municipality", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
