"""transfrs in tickets

Revision ID: 91b560470adf
Revises: f04204888db9
Create Date: 2025-08-10 02:36:27.366839

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91b560470adf"
down_revision: str | None = "f04204888db9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("transfers", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "transfers")
    # ### end Alembic commands ###
