"""Init airlines

Revision ID: 96a36ddfaa14
Revises: 67ef4354ebee
Create Date: 2025-08-09 20:08:20.810185

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96a36ddfaa14"
down_revision: str | None = "67ef4354ebee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airlines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("icao", sa.String(), nullable=True),
        sa.Column("iata", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_airlines_id"), "airlines", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_airlines_id"), table_name="airlines")
    op.drop_table("airlines")
    # ### end Alembic commands ###
