"""english countries

Revision ID: d533a6a57e91
Revises: 0dc7f09d55ea
Create Date: 2025-08-09 23:09:34.596577

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d533a6a57e91"
down_revision: str | None = "0dc7f09d55ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("countries", sa.Column("name_english", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("countries", "name_english")
    # ### end Alembic commands ###
