ALL_TICKETS_MOCK = [
    {
        "id": "a96d3a5b-edc3-44dc-8984-3fd307a46a60",
        "price": "86036.29",
        "currency": "RUB",
        "itineraries": [
            {
                "transfers": 1,
                "segments": [
                    {
                        "flight_number": "QR-338",
                        "segment_number": 1,
                        "destination_airport": {
                            "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                            "name": "Hamad International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                                "iso": "QA",
                                "name": "Катар",
                                "name_english": "Qatar",
                            },
                            "city": {
                                "id": "785ae0dd-88fa-4574-a26c-f309d3e6a577",
                                "name": "Доха",
                                "name_english": "Doha",
                            },
                            "scheduled_service": "yes",
                            "icao": "OTHH",
                            "iata": "DOH",
                            "gps_code": "OTHH",
                            "region": {
                                "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                                "iso": "QA-DA",
                                "name": "Эд-Доха",
                                "name_english": "Doha",
                            },
                            "name_russian": "Международный аэропорт Доха",
                        },
                        "origin_airport": {
                            "id": "bda7b0bf-1163-4f88-a089-73672b892d9d",
                            "name": "Sheremetyevo International Airport",
                            "continent": "EU",
                            "country": {
                                "id": "9189b385-44db-4f74-b766-b60f213737c5",
                                "iso": "RU",
                                "name": "Россия",
                                "name_english": "Russia",
                            },
                            "city": {
                                "id": "68ef468b-9d14-4bb7-97ae-5c503d6abe0d",
                                "name": "Москва",
                                "name_english": "Moscow",
                            },
                            "scheduled_service": "yes",
                            "icao": "UUEE",
                            "iata": "SVO",
                            "gps_code": "UUEE",
                            "region": {
                                "id": "3c236e36-ec1a-4106-9695-4a293d15a12a",
                                "iso": "RU-MOS",
                                "name": "Московская область",
                                "name_english": "Moskovskaya oblast",
                            },
                            "name_russian": "Международный аэропорт Шереметьево",
                        },
                        "airline": {
                            "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                            "iata": "QR",
                            "icao": "QTR",
                            "name": "Qatar Airways",
                            "name_russian": "Катарские Авиалинии",
                        },
                        "aircraft": {"name": "Boeing 787-9 pax", "iata": "789"},
                        "departure_at": "2025-09-19T20:50:00Z",
                        "return_at": "2025-09-20T02:15:00Z",
                        "duration": 325,
                        "status": "confirmed",
                        "seat_class": "economy",
                    },
                    {
                        "flight_number": "QR-1022",
                        "segment_number": 2,
                        "destination_airport": {
                            "id": "20a22957-7d96-4b70-ad81-f35d8f76770b",
                            "name": "Dubai International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "c2a801cb-1ec0-421b-ba4b-975dabc8567e",
                                "iso": "AE",
                                "name": "Объединенные Арабские Эмираты",
                                "name_english": "United Arab Emirates",
                            },
                            "city": {
                                "id": "98bcade0-7839-43a4-90ea-58bf1ca6d954",
                                "name": "Дубай",
                                "name_english": "Dubai",
                            },
                            "scheduled_service": "yes",
                            "icao": "OMDB",
                            "iata": "DXB",
                            "gps_code": "OMDB",
                            "region": {
                                "id": "ba845903-1625-46f6-b74e-ae331dd01b9f",
                                "iso": "AE-DU",
                                "name": "Дубай",
                                "name_english": "Dubai",
                            },
                            "name_russian": None,
                        },
                        "origin_airport": {
                            "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                            "name": "Hamad International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                                "iso": "QA",
                                "name": "Катар",
                                "name_english": "Qatar",
                            },
                            "city": {
                                "id": "785ae0dd-88fa-4574-a26c-f309d3e6a577",
                                "name": "Доха",
                                "name_english": "Doha",
                            },
                            "scheduled_service": "yes",
                            "icao": "OTHH",
                            "iata": "DOH",
                            "gps_code": "OTHH",
                            "region": {
                                "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                                "iso": "QA-DA",
                                "name": "Эд-Доха",
                                "name_english": "Doha",
                            },
                            "name_russian": "Международный аэропорт Доха",
                        },
                        "airline": {
                            "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                            "iata": "QR",
                            "icao": "QTR",
                            "name": "Qatar Airways",
                            "name_russian": "Катарские Авиалинии",
                        },
                        "aircraft": {"name": "Airbus A350-900", "iata": "359"},
                        "departure_at": "2025-09-20T06:20:00Z",
                        "return_at": "2025-09-20T07:40:00Z",
                        "duration": 80,
                        "status": "confirmed",
                        "seat_class": "economy",
                    },
                ],
                "duration": 650,
            },
            {
                "transfers": 1,
                "segments": [
                    {
                        "flight_number": "QR-1023",
                        "segment_number": 1,
                        "destination_airport": {
                            "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                            "name": "Hamad International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                                "iso": "QA",
                                "name": "Катар",
                                "name_english": "Qatar",
                            },
                            "city": {
                                "id": "785ae0dd-88fa-4574-a26c-f309d3e6a577",
                                "name": "Доха",
                                "name_english": "Doha",
                            },
                            "scheduled_service": "yes",
                            "icao": "OTHH",
                            "iata": "DOH",
                            "gps_code": "OTHH",
                            "region": {
                                "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                                "iso": "QA-DA",
                                "name": "Эд-Доха",
                                "name_english": "Doha",
                            },
                            "name_russian": "Международный аэропорт Доха",
                        },
                        "origin_airport": {
                            "id": "20a22957-7d96-4b70-ad81-f35d8f76770b",
                            "name": "Dubai International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "c2a801cb-1ec0-421b-ba4b-975dabc8567e",
                                "iso": "AE",
                                "name": "Объединенные Арабские Эмираты",
                                "name_english": "United Arab Emirates",
                            },
                            "city": {
                                "id": "98bcade0-7839-43a4-90ea-58bf1ca6d954",
                                "name": "Дубай",
                                "name_english": "Dubai",
                            },
                            "scheduled_service": "yes",
                            "icao": "OMDB",
                            "iata": "DXB",
                            "gps_code": "OMDB",
                            "region": {
                                "id": "ba845903-1625-46f6-b74e-ae331dd01b9f",
                                "iso": "AE-DU",
                                "name": "Дубай",
                                "name_english": "Dubai",
                            },
                            "name_russian": None,
                        },
                        "airline": {
                            "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                            "iata": "QR",
                            "icao": "QTR",
                            "name": "Qatar Airways",
                            "name_russian": "Катарские Авиалинии",
                        },
                        "aircraft": {"name": "Boeing 777-300ER pax", "iata": "77W"},
                        "departure_at": "2025-09-27T09:15:00Z",
                        "return_at": "2025-09-27T10:30:00Z",
                        "duration": 75,
                        "status": "confirmed",
                        "seat_class": "economy",
                    },
                    {
                        "flight_number": "QR-337",
                        "segment_number": 2,
                        "destination_airport": {
                            "id": "bda7b0bf-1163-4f88-a089-73672b892d9d",
                            "name": "Sheremetyevo International Airport",
                            "continent": "EU",
                            "country": {
                                "id": "9189b385-44db-4f74-b766-b60f213737c5",
                                "iso": "RU",
                                "name": "Россия",
                                "name_english": "Russia",
                            },
                            "city": {
                                "id": "68ef468b-9d14-4bb7-97ae-5c503d6abe0d",
                                "name": "Москва",
                                "name_english": "Moscow",
                            },
                            "scheduled_service": "yes",
                            "icao": "UUEE",
                            "iata": "SVO",
                            "gps_code": "UUEE",
                            "region": {
                                "id": "3c236e36-ec1a-4106-9695-4a293d15a12a",
                                "iso": "RU-MOS",
                                "name": "Московская область",
                                "name_english": "Moskovskaya oblast",
                            },
                            "name_russian": "Международный аэропорт Шереметьево",
                        },
                        "origin_airport": {
                            "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                            "name": "Hamad International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                                "iso": "QA",
                                "name": "Катар",
                                "name_english": "Qatar",
                            },
                            "city": {
                                "id": "785ae0dd-88fa-4574-a26c-f309d3e6a577",
                                "name": "Доха",
                                "name_english": "Doha",
                            },
                            "scheduled_service": "yes",
                            "icao": "OTHH",
                            "iata": "DOH",
                            "gps_code": "OTHH",
                            "region": {
                                "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                                "iso": "QA-DA",
                                "name": "Эд-Доха",
                                "name_english": "Doha",
                            },
                            "name_russian": "Международный аэропорт Доха",
                        },
                        "airline": {
                            "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                            "iata": "QR",
                            "icao": "QTR",
                            "name": "Qatar Airways",
                            "name_russian": "Катарские Авиалинии",
                        },
                        "aircraft": {"name": "Boeing 787-9 pax", "iata": "789"},
                        "departure_at": "2025-09-27T12:50:00Z",
                        "return_at": "2025-09-27T18:20:00Z",
                        "duration": 330,
                        "status": "confirmed",
                        "seat_class": "economy",
                    },
                ],
                "duration": 545,
            },
        ],
    },
    {
        "id": "fc1bab96-5edb-47cd-98df-08b3ae42e461",
        "price": "86036.29",
        "currency": "RUB",
        "itineraries": [
            {
                "transfers": 1,
                "segments": [
                    {
                        "flight_number": "QR-338",
                        "segment_number": 1,
                        "destination_airport": {
                            "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                            "name": "Hamad International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                                "iso": "QA",
                                "name": "Катар",
                                "name_english": "Qatar",
                            },
                            "city": {
                                "id": "785ae0dd-88fa-4574-a26c-f309d3e6a577",
                                "name": "Доха",
                                "name_english": "Doha",
                            },
                            "scheduled_service": "yes",
                            "icao": "OTHH",
                            "iata": "DOH",
                            "gps_code": "OTHH",
                            "region": {
                                "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                                "iso": "QA-DA",
                                "name": "Эд-Доха",
                                "name_english": "Doha",
                            },
                            "name_russian": "Международный аэропорт Доха",
                        },
                        "origin_airport": {
                            "id": "bda7b0bf-1163-4f88-a089-73672b892d9d",
                            "name": "Sheremetyevo International Airport",
                            "continent": "EU",
                            "country": {
                                "id": "9189b385-44db-4f74-b766-b60f213737c5",
                                "iso": "RU",
                                "name": "Россия",
                                "name_english": "Russia",
                            },
                            "city": {
                                "id": "68ef468b-9d14-4bb7-97ae-5c503d6abe0d",
                                "name": "Москва",
                                "name_english": "Moscow",
                            },
                            "scheduled_service": "yes",
                            "icao": "UUEE",
                            "iata": "SVO",
                            "gps_code": "UUEE",
                            "region": {
                                "id": "3c236e36-ec1a-4106-9695-4a293d15a12a",
                                "iso": "RU-MOS",
                                "name": "Московская область",
                                "name_english": "Moskovskaya oblast",
                            },
                            "name_russian": "Международный аэропорт Шереметьево",
                        },
                        "airline": {
                            "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                            "iata": "QR",
                            "icao": "QTR",
                            "name": "Qatar Airways",
                            "name_russian": "Катарские Авиалинии",
                        },
                        "aircraft": {"name": "Boeing 787-9 pax", "iata": "789"},
                        "departure_at": "2025-09-19T20:50:00Z",
                        "return_at": "2025-09-20T02:15:00Z",
                        "duration": 325,
                        "status": "confirmed",
                        "seat_class": "economy",
                    },
                    {
                        "flight_number": "QR-1022",
                        "segment_number": 2,
                        "destination_airport": {
                            "id": "20a22957-7d96-4b70-ad81-f35d8f76770b",
                            "name": "Dubai International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "c2a801cb-1ec0-421b-ba4b-975dabc8567e",
                                "iso": "AE",
                                "name": "Объединенные Арабские Эмираты",
                                "name_english": "United Arab Emirates",
                            },
                            "city": {
                                "id": "98bcade0-7839-43a4-90ea-58bf1ca6d954",
                                "name": "Дубай",
                                "name_english": "Dubai",
                            },
                            "scheduled_service": "yes",
                            "icao": "OMDB",
                            "iata": "DXB",
                            "gps_code": "OMDB",
                            "region": {
                                "id": "ba845903-1625-46f6-b74e-ae331dd01b9f",
                                "iso": "AE-DU",
                                "name": "Дубай",
                                "name_english": "Dubai",
                            },
                            "name_russian": None,
                        },
                        "origin_airport": {
                            "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                            "name": "Hamad International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                                "iso": "QA",
                                "name": "Катар",
                                "name_english": "Qatar",
                            },
                            "city": {
                                "id": "785ae0dd-88fa-4574-a26c-f309d3e6a577",
                                "name": "Доха",
                                "name_english": "Doha",
                            },
                            "scheduled_service": "yes",
                            "icao": "OTHH",
                            "iata": "DOH",
                            "gps_code": "OTHH",
                            "region": {
                                "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                                "iso": "QA-DA",
                                "name": "Эд-Доха",
                                "name_english": "Doha",
                            },
                            "name_russian": "Международный аэропорт Доха",
                        },
                        "airline": {
                            "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                            "iata": "QR",
                            "icao": "QTR",
                            "name": "Qatar Airways",
                            "name_russian": "Катарские Авиалинии",
                        },
                        "aircraft": {"name": "Airbus A350-900", "iata": "359"},
                        "departure_at": "2025-09-20T06:20:00Z",
                        "return_at": "2025-09-20T07:40:00Z",
                        "duration": 80,
                        "status": "confirmed",
                        "seat_class": "economy",
                    },
                ],
                "duration": 650,
            },
            {
                "transfers": 1,
                "segments": [
                    {
                        "flight_number": "QR-1007",
                        "segment_number": 1,
                        "destination_airport": {
                            "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                            "name": "Hamad International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                                "iso": "QA",
                                "name": "Катар",
                                "name_english": "Qatar",
                            },
                            "city": {
                                "id": "785ae0dd-88fa-4574-a26c-f309d3e6a577",
                                "name": "Доха",
                                "name_english": "Doha",
                            },
                            "scheduled_service": "yes",
                            "icao": "OTHH",
                            "iata": "DOH",
                            "gps_code": "OTHH",
                            "region": {
                                "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                                "iso": "QA-DA",
                                "name": "Эд-Доха",
                                "name_english": "Doha",
                            },
                            "name_russian": "Международный аэропорт Доха",
                        },
                        "origin_airport": {
                            "id": "20a22957-7d96-4b70-ad81-f35d8f76770b",
                            "name": "Dubai International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "c2a801cb-1ec0-421b-ba4b-975dabc8567e",
                                "iso": "AE",
                                "name": "Объединенные Арабские Эмираты",
                                "name_english": "United Arab Emirates",
                            },
                            "city": {
                                "id": "98bcade0-7839-43a4-90ea-58bf1ca6d954",
                                "name": "Дубай",
                                "name_english": "Dubai",
                            },
                            "scheduled_service": "yes",
                            "icao": "OMDB",
                            "iata": "DXB",
                            "gps_code": "OMDB",
                            "region": {
                                "id": "ba845903-1625-46f6-b74e-ae331dd01b9f",
                                "iso": "AE-DU",
                                "name": "Дубай",
                                "name_english": "Dubai",
                            },
                            "name_russian": None,
                        },
                        "airline": {
                            "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                            "iata": "QR",
                            "icao": "QTR",
                            "name": "Qatar Airways",
                            "name_russian": "Катарские Авиалинии",
                        },
                        "aircraft": {"name": "Airbus A330-300", "iata": "333"},
                        "departure_at": "2025-09-27T07:45:00Z",
                        "return_at": "2025-09-27T09:00:00Z",
                        "duration": 75,
                        "status": "confirmed",
                        "seat_class": "economy",
                    },
                    {
                        "flight_number": "QR-337",
                        "segment_number": 2,
                        "destination_airport": {
                            "id": "bda7b0bf-1163-4f88-a089-73672b892d9d",
                            "name": "Sheremetyevo International Airport",
                            "continent": "EU",
                            "country": {
                                "id": "9189b385-44db-4f74-b766-b60f213737c5",
                                "iso": "RU",
                                "name": "Россия",
                                "name_english": "Russia",
                            },
                            "city": {
                                "id": "68ef468b-9d14-4bb7-97ae-5c503d6abe0d",
                                "name": "Москва",
                                "name_english": "Moscow",
                            },
                            "scheduled_service": "yes",
                            "icao": "UUEE",
                            "iata": "SVO",
                            "gps_code": "UUEE",
                            "region": {
                                "id": "3c236e36-ec1a-4106-9695-4a293d15a12a",
                                "iso": "RU-MOS",
                                "name": "Московская область",
                                "name_english": "Moskovskaya oblast",
                            },
                            "name_russian": "Международный аэропорт Шереметьево",
                        },
                        "origin_airport": {
                            "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                            "name": "Hamad International Airport",
                            "continent": "AS",
                            "country": {
                                "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                                "iso": "QA",
                                "name": "Катар",
                                "name_english": "Qatar",
                            },
                            "city": {
                                "id": "785ae0dd-88fa-4574-a26c-f309d3e6a577",
                                "name": "Доха",
                                "name_english": "Doha",
                            },
                            "scheduled_service": "yes",
                            "icao": "OTHH",
                            "iata": "DOH",
                            "gps_code": "OTHH",
                            "region": {
                                "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                                "iso": "QA-DA",
                                "name": "Эд-Доха",
                                "name_english": "Doha",
                            },
                            "name_russian": "Международный аэропорт Доха",
                        },
                        "airline": {
                            "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                            "iata": "QR",
                            "icao": "QTR",
                            "name": "Qatar Airways",
                            "name_russian": "Катарские Авиалинии",
                        },
                        "aircraft": {"name": "Boeing 787-9 pax", "iata": "789"},
                        "departure_at": "2025-09-27T12:50:00Z",
                        "return_at": "2025-09-27T18:20:00Z",
                        "duration": 330,
                        "status": "confirmed",
                        "seat_class": "economy",
                    },
                ],
                "duration": 635,
            },
        ],
    },
]

MOCK_TICKET = {
    "id": "a96d3a5b-edc3-44dc-8984-3fd307a46a60",
    "price": 920.38,
    "currency": "EUR",
    "itineraries": [
        {
            "transfers": 1,
            "segments": [
                {
                    "flight_number": "QR-338",
                    "segment_number": 1,
                    "destination_airport": {
                        "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                        "name": "Hamad International Airport",
                        "continent": "AS",
                        "country": {
                            "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                            "iso": "QA",
                            "name": "Катар",
                            "name_english": "Qatar",
                        },
                        "city": {"id": "785ae0dd-88fa-4574-a26c-f309d3e6a577", "name": "Доха", "name_english": "Doha"},
                        "scheduled_service": "yes",
                        "icao": "OTHH",
                        "iata": "DOH",
                        "gps_code": "OTHH",
                        "region": {
                            "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                            "iso": "QA-DA",
                            "name": "Эд-Доха",
                            "name_english": "Doha",
                        },
                        "name_russian": "Международный аэропорт Доха",
                    },
                    "origin_airport": {
                        "id": "bda7b0bf-1163-4f88-a089-73672b892d9d",
                        "name": "Sheremetyevo International Airport",
                        "continent": "EU",
                        "country": {
                            "id": "9189b385-44db-4f74-b766-b60f213737c5",
                            "iso": "RU",
                            "name": "Россия",
                            "name_english": "Russia",
                        },
                        "city": {
                            "id": "68ef468b-9d14-4bb7-97ae-5c503d6abe0d",
                            "name": "Москва",
                            "name_english": "Moscow",
                        },
                        "scheduled_service": "yes",
                        "icao": "UUEE",
                        "iata": "SVO",
                        "gps_code": "UUEE",
                        "region": {
                            "id": "3c236e36-ec1a-4106-9695-4a293d15a12a",
                            "iso": "RU-MOS",
                            "name": "Московская область",
                            "name_english": "Moskovskaya oblast",
                        },
                        "name_russian": "Международный аэропорт Шереметьево",
                    },
                    "airline": {
                        "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                        "iata": "QR",
                        "icao": "QTR",
                        "name": "Qatar Airways",
                        "name_russian": "Катарские Авиалинии",
                    },
                    "aircraft": {"name": "Boeing 787-9 pax", "iata": "789"},
                    "departure_at": "2025-09-19T20:50:00+00:00",
                    "return_at": "2025-09-20T02:15:00+00:00",
                    "duration": 325,
                    "status": "confirmed",
                    "seat_class": "economy",
                },
                {
                    "flight_number": "QR-1022",
                    "segment_number": 2,
                    "destination_airport": {
                        "id": "20a22957-7d96-4b70-ad81-f35d8f76770b",
                        "name": "Dubai International Airport",
                        "continent": "AS",
                        "country": {
                            "id": "c2a801cb-1ec0-421b-ba4b-975dabc8567e",
                            "iso": "AE",
                            "name": "Объединенные Арабские Эмираты",
                            "name_english": "United Arab Emirates",
                        },
                        "city": {
                            "id": "98bcade0-7839-43a4-90ea-58bf1ca6d954",
                            "name": "Дубай",
                            "name_english": "Dubai",
                        },
                        "scheduled_service": "yes",
                        "icao": "OMDB",
                        "iata": "DXB",
                        "gps_code": "OMDB",
                        "region": {
                            "id": "ba845903-1625-46f6-b74e-ae331dd01b9f",
                            "iso": "AE-DU",
                            "name": "Дубай",
                            "name_english": "Dubai",
                        },
                        "name_russian": None,
                    },
                    "origin_airport": {
                        "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                        "name": "Hamad International Airport",
                        "continent": "AS",
                        "country": {
                            "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                            "iso": "QA",
                            "name": "Катар",
                            "name_english": "Qatar",
                        },
                        "city": {"id": "785ae0dd-88fa-4574-a26c-f309d3e6a577", "name": "Доха", "name_english": "Doha"},
                        "scheduled_service": "yes",
                        "icao": "OTHH",
                        "iata": "DOH",
                        "gps_code": "OTHH",
                        "region": {
                            "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                            "iso": "QA-DA",
                            "name": "Эд-Доха",
                            "name_english": "Doha",
                        },
                        "name_russian": "Международный аэропорт Доха",
                    },
                    "airline": {
                        "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                        "iata": "QR",
                        "icao": "QTR",
                        "name": "Qatar Airways",
                        "name_russian": "Катарские Авиалинии",
                    },
                    "aircraft": {"name": "Airbus A350-900", "iata": "359"},
                    "departure_at": "2025-09-20T06:20:00+00:00",
                    "return_at": "2025-09-20T07:40:00+00:00",
                    "duration": 80,
                    "status": "confirmed",
                    "seat_class": "economy",
                },
            ],
            "duration": 650,
        },
        {
            "transfers": 1,
            "segments": [
                {
                    "flight_number": "QR-1023",
                    "segment_number": 1,
                    "destination_airport": {
                        "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                        "name": "Hamad International Airport",
                        "continent": "AS",
                        "country": {
                            "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                            "iso": "QA",
                            "name": "Катар",
                            "name_english": "Qatar",
                        },
                        "city": {"id": "785ae0dd-88fa-4574-a26c-f309d3e6a577", "name": "Доха", "name_english": "Doha"},
                        "scheduled_service": "yes",
                        "icao": "OTHH",
                        "iata": "DOH",
                        "gps_code": "OTHH",
                        "region": {
                            "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                            "iso": "QA-DA",
                            "name": "Эд-Доха",
                            "name_english": "Doha",
                        },
                        "name_russian": "Международный аэропорт Доха",
                    },
                    "origin_airport": {
                        "id": "20a22957-7d96-4b70-ad81-f35d8f76770b",
                        "name": "Dubai International Airport",
                        "continent": "AS",
                        "country": {
                            "id": "c2a801cb-1ec0-421b-ba4b-975dabc8567e",
                            "iso": "AE",
                            "name": "Объединенные Арабские Эмираты",
                            "name_english": "United Arab Emirates",
                        },
                        "city": {
                            "id": "98bcade0-7839-43a4-90ea-58bf1ca6d954",
                            "name": "Дубай",
                            "name_english": "Dubai",
                        },
                        "scheduled_service": "yes",
                        "icao": "OMDB",
                        "iata": "DXB",
                        "gps_code": "OMDB",
                        "region": {
                            "id": "ba845903-1625-46f6-b74e-ae331dd01b9f",
                            "iso": "AE-DU",
                            "name": "Дубай",
                            "name_english": "Dubai",
                        },
                        "name_russian": None,
                    },
                    "airline": {
                        "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                        "iata": "QR",
                        "icao": "QTR",
                        "name": "Qatar Airways",
                        "name_russian": "Катарские Авиалинии",
                    },
                    "aircraft": {"name": "Boeing 777-300ER pax", "iata": "77W"},
                    "departure_at": "2025-09-27T09:15:00+00:00",
                    "return_at": "2025-09-27T10:30:00+00:00",
                    "duration": 75,
                    "status": "confirmed",
                    "seat_class": "economy",
                },
                {
                    "flight_number": "QR-337",
                    "segment_number": 2,
                    "destination_airport": {
                        "id": "bda7b0bf-1163-4f88-a089-73672b892d9d",
                        "name": "Sheremetyevo International Airport",
                        "continent": "EU",
                        "country": {
                            "id": "9189b385-44db-4f74-b766-b60f213737c5",
                            "iso": "RU",
                            "name": "Россия",
                            "name_english": "Russia",
                        },
                        "city": {
                            "id": "68ef468b-9d14-4bb7-97ae-5c503d6abe0d",
                            "name": "Москва",
                            "name_english": "Moscow",
                        },
                        "scheduled_service": "yes",
                        "icao": "UUEE",
                        "iata": "SVO",
                        "gps_code": "UUEE",
                        "region": {
                            "id": "3c236e36-ec1a-4106-9695-4a293d15a12a",
                            "iso": "RU-MOS",
                            "name": "Московская область",
                            "name_english": "Moskovskaya oblast",
                        },
                        "name_russian": "Международный аэропорт Шереметьево",
                    },
                    "origin_airport": {
                        "id": "21131c03-e842-4e20-b82d-20f3e650a0ce",
                        "name": "Hamad International Airport",
                        "continent": "AS",
                        "country": {
                            "id": "5cf32bc5-ab20-4e1c-a67e-0e88e6d890b7",
                            "iso": "QA",
                            "name": "Катар",
                            "name_english": "Qatar",
                        },
                        "city": {"id": "785ae0dd-88fa-4574-a26c-f309d3e6a577", "name": "Доха", "name_english": "Doha"},
                        "scheduled_service": "yes",
                        "icao": "OTHH",
                        "iata": "DOH",
                        "gps_code": "OTHH",
                        "region": {
                            "id": "2821ead3-66d8-46b6-b564-4960fc78e956",
                            "iso": "QA-DA",
                            "name": "Эд-Доха",
                            "name_english": "Doha",
                        },
                        "name_russian": "Международный аэропорт Доха",
                    },
                    "airline": {
                        "id": "bc444200-eab9-4d76-a6bf-55fdd93a4965",
                        "iata": "QR",
                        "icao": "QTR",
                        "name": "Qatar Airways",
                        "name_russian": "Катарские Авиалинии",
                    },
                    "aircraft": {"name": "Boeing 787-9 pax", "iata": "789"},
                    "departure_at": "2025-09-27T12:50:00+00:00",
                    "return_at": "2025-09-27T18:20:00+00:00",
                    "duration": 330,
                    "status": "confirmed",
                    "seat_class": "economy",
                },
            ],
            "duration": 545,
        },
    ],
}
