"""empty message

Revision ID: 021fcc73f484
Revises: 7b7bca676fa5
Create Date: 2025-08-21 12:56:58.320866

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "021fcc73f484"
down_revision: str | None = "7b7bca676fa5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_tickets_price"), "tickets", ["price"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_price"), table_name="tickets")
    # ### end Alembic commands ###
