"""empty message

Revision ID: 1f3ba094b31f
Revises: d3ff4aa68b37
Create Date: 2025-08-20 00:01:56.894016

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f3ba094b31f"
down_revision: str | None = "d3ff4aa68b37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("seat_class", sa.String(), nullable=True))
    op.drop_column("tickets", "seat_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("seat_status", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("tickets", "seat_class")
    # ### end Alembic commands ###
