"""empty message

Revision ID: 412ec70b2e3b
Revises: 1f3ba094b31f
Create Date: 2025-08-20 01:13:46.117541

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "412ec70b2e3b"
down_revision: str | None = "1f3ba094b31f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticketsegments", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticketsegments", "status")
    # ### end Alembic commands ###
