"""Airline in tickets

Revision ID: 4a0e03ec5b8c
Revises: 96a36ddfaa14
Create Date: 2025-08-09 20:25:55.778744

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a0e03ec5b8c"
down_revision: str | None = "96a36ddfaa14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("airline_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tickets", "airlines", ["airline_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tickets", type_="foreignkey")
    op.drop_column("tickets", "airline_id")
    # ### end Alembic commands ###
