"""empty message

Revision ID: 6f44316bbd5e
Revises: a29a6c2847f1
Create Date: 2025-08-18 22:51:15.589647

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f44316bbd5e"
down_revision: str | None = "a29a6c2847f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "passangers", "expiration_date", existing_type=sa.VARCHAR(), type_=sa.Date(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "passangers", "expiration_date", existing_type=sa.Date(), type_=sa.VARCHAR(), existing_nullable=True
    )
    # ### end Alembic commands ###
