"""empty message

Revision ID: 7b7bca676fa5
Revises: 412ec70b2e3b
Create Date: 2025-08-20 01:15:30.770291

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b7bca676fa5"
down_revision: str | None = "412ec70b2e3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "seat_class")
    op.add_column("ticketsegments", sa.Column("seat_class", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticketsegments", "seat_class")
    op.add_column("tickets", sa.Column("seat_class", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
