"""added indexes

Revision ID: 7f54ac0c4001
Revises: 91b560470adf
Create Date: 2025-08-10 03:05:44.288531

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f54ac0c4001"
down_revision: str | None = "91b560470adf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_airlines_iata"), "airlines", ["iata"], unique=False)
    op.create_index(op.f("ix_airlines_icao"), "airlines", ["icao"], unique=False)
    op.create_index(op.f("ix_airports_country_id"), "airports", ["country_id"], unique=False)
    op.create_index(op.f("ix_airports_iata"), "airports", ["iata"], unique=False)
    op.create_index(op.f("ix_airports_icao"), "airports", ["icao"], unique=False)
    op.create_index(op.f("ix_airports_region_id"), "airports", ["region_id"], unique=False)
    op.create_index(op.f("ix_countries_iso"), "countries", ["iso"], unique=False)
    op.create_index(op.f("ix_regions_country_id"), "regions", ["country_id"], unique=False)
    op.create_index(op.f("ix_regions_iso"), "regions", ["iso"], unique=False)
    op.create_index(op.f("ix_tickets_airline_id"), "tickets", ["airline_id"], unique=False)
    op.create_index(op.f("ix_tickets_destination_airport_id"), "tickets", ["destination_airport_id"], unique=False)
    op.create_index(op.f("ix_tickets_origin_airport_id"), "tickets", ["origin_airport_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_origin_airport_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_destination_airport_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_airline_id"), table_name="tickets")
    op.drop_index(op.f("ix_regions_iso"), table_name="regions")
    op.drop_index(op.f("ix_regions_country_id"), table_name="regions")
    op.drop_index(op.f("ix_countries_iso"), table_name="countries")
    op.drop_index(op.f("ix_airports_region_id"), table_name="airports")
    op.drop_index(op.f("ix_airports_icao"), table_name="airports")
    op.drop_index(op.f("ix_airports_iata"), table_name="airports")
    op.drop_index(op.f("ix_airports_country_id"), table_name="airports")
    op.drop_index(op.f("ix_airlines_icao"), table_name="airlines")
    op.drop_index(op.f("ix_airlines_iata"), table_name="airlines")
    # ### end Alembic commands ###
