"""user tickets

Revision ID: 85f1901fe190
Revises: f75ab9605be8
Create Date: 2025-08-12 02:28:31.393704

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85f1901fe190"
down_revision: str | None = "f75ab9605be8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("passangers", sa.Column("user_ticket_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "passangers", "usertickets", ["user_ticket_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "passangers", type_="foreignkey")
    op.drop_column("passangers", "user_ticket_id")
    # ### end Alembic commands ###
