"""empty message

Revision ID: a29a6c2847f1
Revises: c1a04b876217
Create Date: 2025-08-18 22:48:30.805613

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a29a6c2847f1"
down_revision: str | None = "c1a04b876217"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("passangers", sa.Column("passport", sa.String(), nullable=True))
    op.add_column("passangers", sa.Column("expiration_date", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("passangers", "expiration_date")
    op.drop_column("passangers", "passport")
    # ### end Alembic commands ###
