"""empty message

Revision ID: a4064fd973ee
Revises: 6f44316bbd5e
Create Date: 2025-08-19 07:01:51.897151

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a4064fd973ee"
down_revision: str | None = "6f44316bbd5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticketsegments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin_airport_id", sa.Integer(), nullable=True),
        sa.Column("destination_airport_id", sa.Integer(), nullable=True),
        sa.Column("airline_id", sa.Integer(), nullable=True),
        sa.Column("departure_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("return_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("flight_number", sa.String(), nullable=True),
        sa.Column("ticket_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["airline_id"],
            ["airlines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_airport_id"],
            ["airports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_airport_id"],
            ["airports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticketsegments_airline_id"), "ticketsegments", ["airline_id"], unique=False)
    op.create_index(
        op.f("ix_ticketsegments_destination_airport_id"), "ticketsegments", ["destination_airport_id"], unique=False
    )
    op.create_index(op.f("ix_ticketsegments_id"), "ticketsegments", ["id"], unique=False)
    op.create_index(op.f("ix_ticketsegments_origin_airport_id"), "ticketsegments", ["origin_airport_id"], unique=False)
    op.drop_index("ix_tickets_airline_id", table_name="tickets")
    op.drop_index("ix_tickets_destination_airport_id", table_name="tickets")
    op.drop_index("ix_tickets_origin_airport_id", table_name="tickets")
    op.drop_constraint("tickets_airline_id_fkey", "tickets", type_="foreignkey")
    op.drop_constraint("tickets_destination_airport_id_fkey", "tickets", type_="foreignkey")
    op.drop_constraint("tickets_origin_airport_id_fkey", "tickets", type_="foreignkey")
    op.drop_column("tickets", "destination_airport_id")
    op.drop_column("tickets", "departure_at")
    op.drop_column("tickets", "origin_airport_id")
    op.drop_column("tickets", "airline_id")
    op.drop_column("tickets", "return_at")
    op.drop_column("tickets", "flight_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("flight_number", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "tickets", sa.Column("return_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.add_column("tickets", sa.Column("airline_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("tickets", sa.Column("origin_airport_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "tickets", sa.Column("departure_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.add_column("tickets", sa.Column("destination_airport_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("tickets_origin_airport_id_fkey", "tickets", "airports", ["origin_airport_id"], ["id"])
    op.create_foreign_key(
        "tickets_destination_airport_id_fkey", "tickets", "airports", ["destination_airport_id"], ["id"]
    )
    op.create_foreign_key("tickets_airline_id_fkey", "tickets", "airlines", ["airline_id"], ["id"])
    op.create_index("ix_tickets_origin_airport_id", "tickets", ["origin_airport_id"], unique=False)
    op.create_index("ix_tickets_destination_airport_id", "tickets", ["destination_airport_id"], unique=False)
    op.create_index("ix_tickets_airline_id", "tickets", ["airline_id"], unique=False)
    op.drop_index(op.f("ix_ticketsegments_origin_airport_id"), table_name="ticketsegments")
    op.drop_index(op.f("ix_ticketsegments_id"), table_name="ticketsegments")
    op.drop_index(op.f("ix_ticketsegments_destination_airport_id"), table_name="ticketsegments")
    op.drop_index(op.f("ix_ticketsegments_airline_id"), table_name="ticketsegments")
    op.drop_table("ticketsegments")
    # ### end Alembic commands ###
