"""empty message

Revision ID: d3ff4aa68b37
Revises: a4064fd973ee
Create Date: 2025-08-19 23:59:33.431811

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3ff4aa68b37"
down_revision: str | None = "a4064fd973ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("currency", sa.String(), nullable=True))
    op.add_column("tickets", sa.Column("seat_status", sa.String(), nullable=True))
    op.alter_column("tickets", "price", existing_type=sa.INTEGER(), type_=sa.Float(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tickets", "price", existing_type=sa.Float(), type_=sa.INTEGER(), existing_nullable=True)
    op.drop_column("tickets", "seat_status")
    op.drop_column("tickets", "currency")
    # ### end Alembic commands ###
