"""remove some indexes from airport

Revision ID: d6929e5dcc3a
Revises: 8bbfb0199e05
Create Date: 2025-08-10 19:08:56.937933

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6929e5dcc3a"
down_revision: str | None = "8bbfb0199e05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_airports_country_id", table_name="airports")
    op.drop_index("ix_airports_region_id", table_name="airports")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_airports_region_id", "airports", ["region_id"], unique=False)
    op.create_index("ix_airports_country_id", "airports", ["country_id"], unique=False)
    # ### end Alembic commands ###
