"""user updates

Revision ID: dcac0c1db06c
Revises: d6929e5dcc3a
Create Date: 2025-08-11 22:07:44.407912

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcac0c1db06c"
down_revision: str | None = "d6929e5dcc3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("second_name", sa.String(), nullable=True))
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("user", "second_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
