"""russian name in airlines

Revision ID: f04204888db9
Revises: 6386416f5fe5
Create Date: 2025-08-10 01:30:32.717610

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f04204888db9"
down_revision: str | None = "6386416f5fe5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("airlines", sa.Column("name_russian", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("airlines", "name_russian")
    # ### end Alembic commands ###
