"""user tickets

Revision ID: f75ab9605be8
Revises: dcac0c1db06c
Create Date: 2025-08-12 02:26:07.757740

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f75ab9605be8"
down_revision: str | None = "dcac0c1db06c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passangers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("second_name", sa.String(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_passangers_id"), "passangers", ["id"], unique=False)
    op.create_table(
        "usertickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("ticket_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usertickets_id"), "usertickets", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usertickets_id"), table_name="usertickets")
    op.drop_table("usertickets")
    op.drop_index(op.f("ix_passangers_id"), table_name="passangers")
    op.drop_table("passangers")
    # ### end Alembic commands ###
