"""empty message

Revision ID: 01cbe402d485
Revises: 76e17bda1f81
Create Date: 2025-09-02 19:30:33.937398

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01cbe402d485"
down_revision: str | None = "76e17bda1f81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "duration")
    op.drop_column("tickets", "transfers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("transfers", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("tickets", sa.Column("duration", sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
