"""empty message

Revision ID: 3510c8176c99
Revises: 370d422c6d83
Create Date: 2025-09-03 12:54:20.559812

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3510c8176c99"
down_revision: str | None = "370d422c6d83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("unique_key_int", sa.Integer(), nullable=True))
    op.drop_constraint("tickets_unique_key_key", "tickets", type_="unique")
    op.create_unique_constraint(None, "tickets", ["unique_key_int"])
    op.drop_column("tickets", "unique_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("unique_key", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "tickets", type_="unique")
    op.create_unique_constraint("tickets_unique_key_key", "tickets", ["unique_key"])
    op.drop_column("tickets", "unique_key_int")
    # ### end Alembic commands ###
