"""empty message

Revision ID: 76e17bda1f81
Revises: ae106791f9f1
Create Date: 2025-09-02 18:13:00.162584

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76e17bda1f81"
down_revision: str | None = "ae106791f9f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("unique_key", sa.String(), nullable=True))
    op.create_unique_constraint(None, "tickets", ["unique_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tickets", type_="unique")
    op.drop_column("tickets", "unique_key")
    # ### end Alembic commands ###
