"""empty message

Revision ID: 833b0e9ce811
Revises: 9be5d02d7768
Create Date: 2025-09-09 21:57:00.029228

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "833b0e9ce811"
down_revision: str | None = "9be5d02d7768"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contract", sa.String(), nullable=True),
        sa.Column("insured_id", sa.UUID(), nullable=True),
        sa.Column("premium_value", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("premium_currency", sa.String(), nullable=True),
        sa.Column("created_at", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["insured_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract"),
    )
    op.create_table(
        "pdfinsurances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("insurance_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("content_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["insurance_id"],
            ["insurances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pdfinsurances")
    op.drop_table("insurances")
    # ### end Alembic commands ###
