"""empty message

Revision ID: 8a21a7591172
Revises: 5936f923b26e
Create Date: 2025-09-11 15:57:18.127442

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a21a7591172"
down_revision: str | None = "5936f923b26e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("birth_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "birth_date")
    # ### end Alembic commands ###
