"""empty message

Revision ID: 1490584b45e7
Revises: bc946cfd6247
Create Date: 2025-09-17 22:57:02.997718

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1490584b45e7"
down_revision: str | None = "bc946cfd6247"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticketsegments", sa.Column("aircraft_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "ticketsegments", "aircrafts", ["aircraft_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ticketsegments", type_="foreignkey")
    op.drop_column("ticketsegments", "aircraft_id")
    # ### end Alembic commands ###
