"""empty message

Revision ID: 370d422c6d83
Revises: 01cbe402d485
Create Date: 2025-09-03 12:49:00.480002

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "370d422c6d83"
down_revision: str | None = "01cbe402d485"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('tickets', 'unique_key',
    #           existing_type=sa.VARCHAR(),
    #           type_=sa.Integer(),
    #           existing_nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tickets", "unique_key", existing_type=sa.Integer(), type_=sa.VARCHAR(), existing_nullable=True)
    # ### end Alembic commands ###
