"""empty message

Revision ID: 5936f923b26e
Revises: 833b0e9ce811
Create Date: 2025-09-09 23:56:59.618940

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5936f923b26e"
down_revision: str | None = "833b0e9ce811"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("insurances", sa.Column("territory", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("insurances", "territory")
    # ### end Alembic commands ###
