"""empty message

Revision ID: 8353933d0de0
Revises: aa4519f6f3cd
Create Date: 2025-08-24 16:13:29.198653

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8353933d0de0"
down_revision: str | None = "aa4519f6f3cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passengers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_ticket_id", sa.UUID(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("second_name", sa.String(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("passport", sa.String(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_ticket_id"],
            ["usertickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("passangers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passangers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_ticket_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("gender", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("second_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("birth_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("passport", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("expiration_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_ticket_id"], ["usertickets.id"], name="passangers_user_ticket_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="passangers_pkey"),
    )
    op.drop_table("passengers")
    # ### end Alembic commands ###
