"""empty message

Revision ID: 856f3428210a
Revises: 82282e5c01c3
Create Date: 2025-09-03 13:00:56.876448

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "856f3428210a"
down_revision: str | None = "82282e5c01c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tickets", "unique_key", existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tickets", "unique_key", existing_type=sa.String(), type_=sa.INTEGER(), existing_nullable=True)
    # ### end Alembic commands ###
