"""empty message

Revision ID: 9be5d02d7768
Revises: 856f3428210a
Create Date: 2025-09-06 19:59:10.653552

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9be5d02d7768"
down_revision: str | None = "856f3428210a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pdftickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_ticket_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("content_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_ticket_id"],
            ["usertickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pdftickets")
    # ### end Alembic commands ###
