"""empty message

Revision ID: aa4519f6f3cd
Revises: 01d37a839612
Create Date: 2025-08-23 05:09:51.805106

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa4519f6f3cd"
down_revision: str | None = "01d37a839612"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticketsegments", sa.Column("segment_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticketsegments", "segment_number")
    # ### end Alembic commands ###
