"""empty message

Revision ID: ae106791f9f1
Revises: 8353933d0de0
Create Date: 2025-09-01 19:44:32.957717

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae106791f9f1"
down_revision: str | None = "8353933d0de0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticketitineraries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("ticket_id", sa.UUID(), nullable=True),
        sa.Column("transfers", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "tickets",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.add_column("ticketsegments", sa.Column("ticket_itinerary_id", sa.UUID(), nullable=True))
    op.drop_constraint("ticketsegments_ticket_id_fkey", "ticketsegments", type_="foreignkey")
    op.create_foreign_key(None, "ticketsegments", "ticketitineraries", ["ticket_itinerary_id"], ["id"])
    op.drop_column("ticketsegments", "ticket_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticketsegments", sa.Column("ticket_id", sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "ticketsegments", type_="foreignkey")
    op.create_foreign_key("ticketsegments_ticket_id_fkey", "ticketsegments", "tickets", ["ticket_id"], ["id"])
    op.drop_column("ticketsegments", "ticket_itinerary_id")
    op.alter_column(
        "tickets",
        "price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_table("ticketitineraries")
    # ### end Alembic commands ###
