"""empty message

Revision ID: bc946cfd6247
Revises: 8a21a7591172
Create Date: 2025-09-17 18:57:44.095343

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc946cfd6247"
down_revision: str | None = "8a21a7591172"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aircrafts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("wtc", sa.String(), nullable=True),
        sa.Column("iata", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_aircrafts_iata"), "aircrafts", ["iata"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_aircrafts_iata"), table_name="aircrafts")
    op.drop_table("aircrafts")
    # ### end Alembic commands ###
